name: Push latest
on:
  push:
    tags:
      - latest
jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
    - name: Copia repositorio
      uses: actions/checkout@v2
    - name: Construye imagen
      run: docker build --tag evaristor/optica:latest --tag evaristor/optica:${GITHUB_SHA:0:4} .
    - name: Docker log-in
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
    - name: Sube latest a Docker Hub
      run: docker push evaristor/optica:latest
    - name: Sube sha a Docker Hub
      run: docker push evaristor/optica:${GITHUB_SHA:0:4}
